### ISSUE TITLE
Demand Hub

### ISSUE THREAD

**Issue by derFunk** [derFunk/monit-windows-agent#1]
Please comment if this is of interest for you and if you want to contribute...

**Comment by Przecinit** [comment]
Hi, when im running  MonitorWinowsAgent.exe from console everything work fine, but when starting as a service says:

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\agentos\docs\%HOMEDRIVE%%HOMEPATH%.monit.id'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at System.IO.File.WriteAllText(String path, String contents)
   at ChMonitoring.Helpers.UniqueWindowsId.GetOrCreateUniqueId() in c:\agentos\ChMonitWindowsAgent\Helpers\UniqueWindowsId.cs:line 24
   at ChMonitoring.MonitWindowsAgent.GetStatusXmlData() in c:\agentos\ChMonitWindowsAgent\MonitWindowsAgent.cs:line 117
   at ChMonitoring.MonitLogic.MMonitClient.Push() in c:\agentos\ChMonitWindowsAgent\MonitLogic\MMonitClient.cs:line 23
   at ChMonitoring.MonitWindowsAgent.DoPeriodicCheck(Object sender, ElapsedEventArgs e) in c:\agentos\ChMonitWindowsAgent\MonitWindowsAgent.cs:line 89
   at ChMonitoring.MonitWindowsAgent.Start() in c:\agentos\ChMonitWindowsAgent\MonitWindowsAgent.cs:line 110
   at ChMonitoring.MonitWindowsAgentService.OnStart(String[] args) in c:\agentos\ChMonitWindowsAgent\Service.cs:line 60
   at ChMonitoring.MonitWindowsAgentService.Start() in c:\agentos\ChMonitWindowsAgent\Service.cs:line 53
   at ChMonitoring.Program.Main(String[] args) in c:\agentos\ChMonitWindowsAgent\Program.cs:line 28

**Comment by makvack** [comment]
Same here, it is just "..starting", but gives error that the service could not be started after a while.

**Comment by derFunk** [comment]
Sorry guys, this project is currently on hold due to lack of time. Feel free to contribute PRs though! I'd be happy to merge.

**Comment by m4x1202** [comment]
- Fixed in the newest version
